org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=8G -XX:ReservedCodeCacheSize=1G -XX:+HeapDumpOnOutOfMemoryError
# -XX:+UseParallelGC
android.useAndroidX=true

#caching and parallel build
org.gradle.caching=true
org.gradle.parallel=true

#keep cache across daemon restarts
# org.gradle.caching.debug=true
# org.gradle.configuration-cache=true
# org.gradle.unsafe.configuration-cache=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
